apiVersion: v1
kind: Service
metadata:
  name: bluegreenlb
  labels:
    app: bluegreenlb
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000
      protocol: TCP
  selector:
    app: blue